const JSONDATA = [
  {
    id: 1,
    first_name: "Brandy",
    last_name: "Hanford",
    email: "bhanford0@delicious.com",
    gender: "Male",
    city: "Tanahbeureum",
  },
  {
    id: 2,
    first_name: "Harriette",
    last_name: "Leggatt",
    email: "hleggatt1@unblog.fr",
    gender: "Female",
    city: "Spitsevka",
  },
  {
    id: 3,
    first_name: "Alleyn",
    last_name: "Carmichael",
    email: "acarmichael2@washingtonpost.com",
    gender: "Male",
    city: "Kotovs’k",
  },
  {
    id: 4,
    first_name: "Lanie",
    last_name: "Southcombe",
    email: "lsouthcombe3@g.co",
    gender: "Male",
    city: "Staryye Atagi",
  },
  {
    id: 5,
    first_name: "Clementia",
    last_name: "Bickerdike",
    email: "cbickerdike4@springer.com",
    gender: "Female",
    city: "Xiaopingba",
  },
  {
    id: 6,
    first_name: "Lesya",
    last_name: "Regan",
    email: "lregan5@timesonline.co.uk",
    gender: "Female",
    city: "Otaniemi",
  },
  {
    id: 7,
    first_name: "Odella",
    last_name: "Sherebrook",
    email: "osherebrook6@mapquest.com",
    gender: "Female",
    city: "Pakkat",
  },
  {
    id: 8,
    first_name: "Noe",
    last_name: "Trengrouse",
    email: "ntrengrouse7@mashable.com",
    gender: "Male",
    city: "Utrecht (stad)",
  },
  {
    id: 9,
    first_name: "Dun",
    last_name: "Outerbridge",
    email: "douterbridge8@trellian.com",
    gender: "Male",
    city: "Xintang",
  },
  {
    id: 10,
    first_name: "Wilton",
    last_name: "Durek",
    email: "wdurek9@cam.ac.uk",
    gender: "Male",
    city: "Paracatu",
  },
  {
    id: 11,
    first_name: "Yorgos",
    last_name: "Hockell",
    email: "yhockella@cnbc.com",
    gender: "Male",
    city: "Jarānwāla",
  },
  {
    id: 12,
    first_name: "Willis",
    last_name: "Huortic",
    email: "whuorticb@europa.eu",
    gender: "Male",
    city: "Khorlovo",
  },
  {
    id: 13,
    first_name: "Jayme",
    last_name: "Calterone",
    email: "jcalteronec@odnoklassniki.ru",
    gender: "Female",
    city: "Shushi",
  },
  {
    id: 14,
    first_name: "Kassi",
    last_name: "Dyke",
    email: "kdyked@ftc.gov",
    gender: "Female",
    city: "Changtan",
  },
  {
    id: 15,
    first_name: "Eleanore",
    last_name: "Whitechurch",
    email: "ewhitechurche@nyu.edu",
    gender: "Female",
    city: "Frei",
  },
  {
    id: 16,
    first_name: "Bonnee",
    last_name: "Amys",
    email: "bamysf@java.com",
    gender: "Female",
    city: "Yudong",
  },
  {
    id: 17,
    first_name: "Anatola",
    last_name: "Luker",
    email: "alukerg@miitbeian.gov.cn",
    gender: "Female",
    city: "Kumanis",
  },
  {
    id: 18,
    first_name: "Desiri",
    last_name: "Manners",
    email: "dmannersh@columbia.edu",
    gender: "Female",
    city: "Philadelphia",
  },
  {
    id: 19,
    first_name: "Ara",
    last_name: "Solly",
    email: "asollyi@elegantthemes.com",
    gender: "Male",
    city: "Tomobe",
  },
  {
    id: 20,
    first_name: "Tanner",
    last_name: "Silson",
    email: "tsilsonj@wikia.com",
    gender: "Male",
    city: "As Sūsah",
  },
  {
    id: 21,
    first_name: "Vito",
    last_name: "George",
    email: "vgeorgek@typepad.com",
    gender: "Male",
    city: "Fengping",
  },
  {
    id: 22,
    first_name: "Noelyn",
    last_name: "Moralee",
    email: "nmoraleel@nytimes.com",
    gender: "Female",
    city: "Iracemápolis",
  },
  {
    id: 23,
    first_name: "Phillie",
    last_name: "Huntingford",
    email: "phuntingfordm@prnewswire.com",
    gender: "Female",
    city: "Airuk",
  },
  {
    id: 24,
    first_name: "Rozalie",
    last_name: "Gosswell",
    email: "rgosswelln@narod.ru",
    gender: "Female",
    city: "Shushicë",
  },
  {
    id: 25,
    first_name: "Emmi",
    last_name: "Greim",
    email: "egreimo@google.com.hk",
    gender: "Female",
    city: "Matnah",
  },
  {
    id: 26,
    first_name: "Bernardo",
    last_name: "Storrock",
    email: "bstorrockp@devhub.com",
    gender: "Male",
    city: "Smoky Lake",
  },
  {
    id: 27,
    first_name: "Arni",
    last_name: "Ezele",
    email: "aezeleq@europa.eu",
    gender: "Male",
    city: "Birao",
  },
  {
    id: 28,
    first_name: "Waylon",
    last_name: "Jelk",
    email: "wjelkr@mashable.com",
    gender: "Male",
    city: "Pangkalanbuun",
  },
  {
    id: 29,
    first_name: "Sonnie",
    last_name: "Ambrogelli",
    email: "sambrogellis@google.nl",
    gender: "Male",
    city: "Aranos",
  },
  {
    id: 30,
    first_name: "Pooh",
    last_name: "Ionn",
    email: "pionnt@bloglines.com",
    gender: "Male",
    city: "Šentilj v Slov. Goricah",
  },
  {
    id: 31,
    first_name: "Massimo",
    last_name: "McNirlan",
    email: "mmcnirlanu@cbc.ca",
    gender: "Male",
    city: "Maués",
  },
  {
    id: 32,
    first_name: "Harlie",
    last_name: "Scahill",
    email: "hscahillv@mit.edu",
    gender: "Female",
    city: "Huazhaizi",
  },
  {
    id: 33,
    first_name: "Ursola",
    last_name: "Vosper",
    email: "uvosperw@com.com",
    gender: "Female",
    city: "Lapi",
  },
  {
    id: 34,
    first_name: "Wolfy",
    last_name: "Cosbey",
    email: "wcosbeyx@walmart.com",
    gender: "Male",
    city: "Ridder",
  },
  {
    id: 35,
    first_name: "Dorothea",
    last_name: "Steynor",
    email: "dsteynory@msu.edu",
    gender: "Female",
    city: "Poissy",
  },
  {
    id: 36,
    first_name: "Constantine",
    last_name: "Beeke",
    email: "cbeekez@nasa.gov",
    gender: "Female",
    city: "Parabcan",
  },
  {
    id: 37,
    first_name: "Patricio",
    last_name: "Bringloe",
    email: "pbringloe10@geocities.com",
    gender: "Male",
    city: "Newark",
  },
  {
    id: 38,
    first_name: "Sosanna",
    last_name: "Copeman",
    email: "scopeman11@privacy.gov.au",
    gender: "Female",
    city: "Charlotte",
  },
  {
    id: 39,
    first_name: "Gerek",
    last_name: "Preene",
    email: "gpreene12@gov.uk",
    gender: "Male",
    city: "Rivesaltes",
  },
  {
    id: 40,
    first_name: "Dulce",
    last_name: "Addicott",
    email: "daddicott13@chicagotribune.com",
    gender: "Female",
    city: "Murcia",
  },
  {
    id: 41,
    first_name: "Worth",
    last_name: "Marushak",
    email: "wmarushak14@rediff.com",
    gender: "Male",
    city: "Recarei",
  },
  {
    id: 42,
    first_name: "Tanney",
    last_name: "Rozec",
    email: "trozec15@imdb.com",
    gender: "Male",
    city: "Tournavista",
  },
  {
    id: 43,
    first_name: "Germaine",
    last_name: "Bretherick",
    email: "gbretherick16@mediafire.com",
    gender: "Male",
    city: "Foumban",
  },
  {
    id: 44,
    first_name: "Andie",
    last_name: "Welden",
    email: "awelden17@so-net.ne.jp",
    gender: "Female",
    city: "Karlskoga",
  },
  {
    id: 45,
    first_name: "Reina",
    last_name: "Nuttall",
    email: "rnuttall18@pbs.org",
    gender: "Female",
    city: "Kayanza",
  },
  {
    id: 46,
    first_name: "Yancy",
    last_name: "Cowley",
    email: "ycowley19@surveymonkey.com",
    gender: "Male",
    city: "Utama Wetan",
  },
  {
    id: 47,
    first_name: "Lauree",
    last_name: "Slavin",
    email: "lslavin1a@yahoo.com",
    gender: "Female",
    city: "Youxi",
  },
  {
    id: 48,
    first_name: "Briney",
    last_name: "Di Maria",
    email: "bdimaria1b@acquirethisname.com",
    gender: "Female",
    city: "Ji Paraná",
  },
  {
    id: 49,
    first_name: "Lind",
    last_name: "Nolleth",
    email: "lnolleth1c@state.tx.us",
    gender: "Male",
    city: "Brzączowice",
  },
  {
    id: 50,
    first_name: "Sela",
    last_name: "Spacie",
    email: "sspacie1d@dmoz.org",
    gender: "Female",
    city: "Sabi",
  },
  {
    id: 51,
    first_name: "Gerhard",
    last_name: "Bulfield",
    email: "gbulfield1e@ftc.gov",
    gender: "Male",
    city: "Sumurgeneng",
  },
  {
    id: 52,
    first_name: "Bernardina",
    last_name: "Hardington",
    email: "bhardington1f@unc.edu",
    gender: "Female",
    city: "General Ramírez",
  },
  {
    id: 53,
    first_name: "Else",
    last_name: "Paschek",
    email: "epaschek1g@wordpress.com",
    gender: "Female",
    city: "San Juan de los Morros",
  },
  {
    id: 54,
    first_name: "Guido",
    last_name: "Overy",
    email: "govery1h@ebay.co.uk",
    gender: "Male",
    city: "Al Fākhūrah",
  },
  {
    id: 55,
    first_name: "Patrick",
    last_name: "Ferneyhough",
    email: "pferneyhough1i@ovh.net",
    gender: "Male",
    city: "Tanagara",
  },
  {
    id: 56,
    first_name: "Agnesse",
    last_name: "Ramsdell",
    email: "aramsdell1j@skyrock.com",
    gender: "Female",
    city: "Maojiagang",
  },
  {
    id: 57,
    first_name: "Seline",
    last_name: "Wrates",
    email: "swrates1k@go.com",
    gender: "Female",
    city: "Hrazdan",
  },
  {
    id: 58,
    first_name: "Herschel",
    last_name: "Dyka",
    email: "hdyka1l@skyrock.com",
    gender: "Male",
    city: "Água Levada",
  },
  {
    id: 59,
    first_name: "Sayres",
    last_name: "McGebenay",
    email: "smcgebenay1m@hexun.com",
    gender: "Male",
    city: "Malausma Kidul",
  },
  {
    id: 60,
    first_name: "Cammy",
    last_name: "Huffadine",
    email: "chuffadine1n@homestead.com",
    gender: "Female",
    city: "Zamboanga",
  },
  {
    id: 61,
    first_name: "Allegra",
    last_name: "Whittington",
    email: "awhittington1o@bloomberg.com",
    gender: "Female",
    city: "Guarapuava",
  },
  {
    id: 62,
    first_name: "Dario",
    last_name: "Pinard",
    email: "dpinard1p@cpanel.net",
    gender: "Male",
    city: "Oliveirinha",
  },
  {
    id: 63,
    first_name: "Barry",
    last_name: "Verman",
    email: "bverman1q@google.pl",
    gender: "Male",
    city: "Arboga",
  },
  {
    id: 64,
    first_name: "Cornall",
    last_name: "MacAlpine",
    email: "cmacalpine1r@dion.ne.jp",
    gender: "Male",
    city: "Straszydle",
  },
  {
    id: 65,
    first_name: "Ephrayim",
    last_name: "Crinkley",
    email: "ecrinkley1s@naver.com",
    gender: "Male",
    city: "Lete",
  },
  {
    id: 66,
    first_name: "Skippy",
    last_name: "Doorey",
    email: "sdoorey1t@nps.gov",
    gender: "Male",
    city: "Nanjia",
  },
  {
    id: 67,
    first_name: "Eryn",
    last_name: "Santo",
    email: "esanto1u@shutterfly.com",
    gender: "Female",
    city: "Tosu",
  },
  {
    id: 68,
    first_name: "Graeme",
    last_name: "Feige",
    email: "gfeige1v@miitbeian.gov.cn",
    gender: "Male",
    city: "Ambarita",
  },
  {
    id: 69,
    first_name: "Corrie",
    last_name: "Doig",
    email: "cdoig1w@github.io",
    gender: "Female",
    city: "Suicheng",
  },
  {
    id: 70,
    first_name: "Dorri",
    last_name: "Iannelli",
    email: "diannelli1x@businessinsider.com",
    gender: "Female",
    city: "Sehwān",
  },
  {
    id: 71,
    first_name: "Warren",
    last_name: "Ardling",
    email: "wardling1y@yahoo.co.jp",
    gender: "Male",
    city: "Jiangjiazui",
  },
  {
    id: 72,
    first_name: "Bald",
    last_name: "Bly",
    email: "bbly1z@biblegateway.com",
    gender: "Male",
    city: "Zunilito",
  },
  {
    id: 73,
    first_name: "Paige",
    last_name: "Ezzy",
    email: "pezzy20@dmoz.org",
    gender: "Male",
    city: "Svislach",
  },
  {
    id: 74,
    first_name: "Millard",
    last_name: "Pawden",
    email: "mpawden21@plala.or.jp",
    gender: "Male",
    city: "Passos",
  },
  {
    id: 75,
    first_name: "Blane",
    last_name: "Iseton",
    email: "biseton22@booking.com",
    gender: "Male",
    city: "Saint-Denis",
  },
  {
    id: 76,
    first_name: "Mabel",
    last_name: "Scones",
    email: "mscones23@xrea.com",
    gender: "Female",
    city: "Hualian",
  },
  {
    id: 77,
    first_name: "Glyn",
    last_name: "Leefe",
    email: "gleefe24@blogtalkradio.com",
    gender: "Male",
    city: "Hino",
  },
  {
    id: 78,
    first_name: "Sal",
    last_name: "Theaker",
    email: "stheaker25@miitbeian.gov.cn",
    gender: "Male",
    city: "Pandasan",
  },
  {
    id: 79,
    first_name: "Pepi",
    last_name: "Casassa",
    email: "pcasassa26@lycos.com",
    gender: "Female",
    city: "Cibugel",
  },
  {
    id: 80,
    first_name: "Palm",
    last_name: "Ellyatt",
    email: "pellyatt27@soundcloud.com",
    gender: "Male",
    city: "Ferraz de Vasconcelos",
  },
  {
    id: 81,
    first_name: "Neysa",
    last_name: "Romei",
    email: "nromei28@homestead.com",
    gender: "Female",
    city: "Batutua",
  },
  {
    id: 82,
    first_name: "Valaria",
    last_name: "Jillitt",
    email: "vjillitt29@discovery.com",
    gender: "Female",
    city: "Stutterheim",
  },
  {
    id: 83,
    first_name: "Ferne",
    last_name: "Maunton",
    email: "fmaunton2a@imgur.com",
    gender: "Female",
    city: "Shibi",
  },
  {
    id: 84,
    first_name: "Harlin",
    last_name: "Tallant",
    email: "htallant2b@squidoo.com",
    gender: "Male",
    city: "Jönköping",
  },
  {
    id: 85,
    first_name: "Jillane",
    last_name: "Dewerson",
    email: "jdewerson2c@ted.com",
    gender: "Female",
    city: "Sandweiler",
  },
  {
    id: 86,
    first_name: "Nerti",
    last_name: "Huggett",
    email: "nhuggett2d@prlog.org",
    gender: "Female",
    city: "Chengdong",
  },
  {
    id: 87,
    first_name: "Elnora",
    last_name: "Royall",
    email: "eroyall2e@addthis.com",
    gender: "Female",
    city: "Contagem",
  },
  {
    id: 88,
    first_name: "Iorgo",
    last_name: "Maffin",
    email: "imaffin2f@booking.com",
    gender: "Male",
    city: "Pinaring",
  },
  {
    id: 89,
    first_name: "Terrence",
    last_name: "Copson",
    email: "tcopson2g@linkedin.com",
    gender: "Male",
    city: "Cineumbeuy",
  },
  {
    id: 90,
    first_name: "Meier",
    last_name: "Acreman",
    email: "macreman2h@hubpages.com",
    gender: "Male",
    city: "Teresópolis",
  },
  {
    id: 91,
    first_name: "Simone",
    last_name: "Chasteney",
    email: "schasteney2i@webmd.com",
    gender: "Male",
    city: "Volochys’k",
  },
  {
    id: 92,
    first_name: "Melisande",
    last_name: "McClunaghan",
    email: "mmcclunaghan2j@edublogs.org",
    gender: "Female",
    city: "Miguel Hidalgo",
  },
  {
    id: 93,
    first_name: "Ashely",
    last_name: "State",
    email: "astate2k@earthlink.net",
    gender: "Female",
    city: "Lumbang",
  },
  {
    id: 94,
    first_name: "Harmon",
    last_name: "Bore",
    email: "hbore2l@ebay.com",
    gender: "Male",
    city: "Rostov-na-Donu",
  },
  {
    id: 95,
    first_name: "Ham",
    last_name: "Mibourne",
    email: "hmibourne2m@msu.edu",
    gender: "Male",
    city: "Cigedang",
  },
  {
    id: 96,
    first_name: "Kennan",
    last_name: "Moquin",
    email: "kmoquin2n@sciencedirect.com",
    gender: "Male",
    city: "Parigi",
  },
  {
    id: 97,
    first_name: "Henderson",
    last_name: "Correa",
    email: "hcorrea2o@jugem.jp",
    gender: "Male",
    city: "Lysogorskaya",
  },
  {
    id: 98,
    first_name: "Sandro",
    last_name: "Biggans",
    email: "sbiggans2p@msn.com",
    gender: "Male",
    city: "Xiwei",
  },
  {
    id: 99,
    first_name: "Geneva",
    last_name: "Leyborne",
    email: "gleyborne2q@go.com",
    gender: "Female",
    city: "Grabovci",
  },
  {
    id: 100,
    first_name: "Moe",
    last_name: "Malarkey",
    email: "mmalarkey2r@devhub.com",
    gender: "Male",
    city: "Xincheng",
  },
];

const STOCKJSON = [{"id":1,"market cap in $":277,"stock price in $":"5.85","company name":"Quaker Chemical Corporation","company industry":"Major Chemicals"},
{"id":2,"market cap in $":191,"stock price in $":"3.55","company name":"Tile Shop Hldgs, Inc.","company industry":"Home Furnishings"},
{"id":3,"market cap in $":266,"stock price in $":"4.48","company name":"Eaton Vance NextShares Trust","company industry":"n/a"},
{"id":4,"market cap in $":207,"stock price in $":"6.30","company name":"Grupo Financiero Galicia S.A.","company industry":"Commercial Banks"},
{"id":5,"market cap in $":291,"stock price in $":"4.08","company name":"First Trust Germany AlphaDEX Fund","company industry":"n/a"},
{"id":6,"market cap in $":242,"stock price in $":"8.50","company name":"Lifetime Brands, Inc.","company industry":"Industrial Machinery/Components"},
{"id":7,"market cap in $":138,"stock price in $":"3.54","company name":"PartnerRe Ltd.","company industry":"n/a"},
{"id":8,"market cap in $":109,"stock price in $":"5.60","company name":"Maxwell Technologies, Inc.","company industry":"Industrial Machinery/Components"},
{"id":9,"market cap in $":155,"stock price in $":"6.68","company name":"Unisys Corporation","company industry":"EDP Services"},
{"id":10,"market cap in $":190,"stock price in $":"2.64","company name":"Global Eagle Entertainment Inc.","company industry":"Telecommunications Equipment"},
{"id":11,"market cap in $":194,"stock price in $":"8.97","company name":"Resource Capital Corp.","company industry":"Real Estate Investment Trusts"},
{"id":12,"market cap in $":230,"stock price in $":"4.99","company name":"Bio-Path Holdings, Inc.","company industry":"Major Pharmaceuticals"},
{"id":13,"market cap in $":288,"stock price in $":"7.20","company name":"Iridium Communications Inc","company industry":"Telecommunications Equipment"},
{"id":14,"market cap in $":238,"stock price in $":"4.66","company name":"Sasol Ltd.","company industry":"Oil & Gas Production"},
{"id":15,"market cap in $":246,"stock price in $":"6.75","company name":"Public Storage","company industry":"Real Estate Investment Trusts"},
{"id":16,"market cap in $":220,"stock price in $":"6.12","company name":"Fortive Corporation","company industry":"Industrial Machinery/Components"},
{"id":17,"market cap in $":239,"stock price in $":"5.20","company name":"Texas Pacific Land Trust","company industry":"Oil & Gas Production"},
{"id":18,"market cap in $":145,"stock price in $":"0.69","company name":"PLDT Inc.","company industry":"Telecommunications Equipment"},
{"id":19,"market cap in $":107,"stock price in $":"5.85","company name":"Inpixon ","company industry":"EDP Services"},
{"id":20,"market cap in $":102,"stock price in $":"5.74","company name":"National American University Holdings, Inc.","company industry":"Other Consumer Services"}];

var T1 = new sheet3({
  id: "t1",
  row: 100,
  col: 6,
  type: "edit",
  location: "T1",
  style: "MD",
  mode: "horzontial",
  data: JSONDATA,
});
T1.createTable();
T1.showRow(1, 20);
let table = document.getElementById("t1");

function showRows(start, end) {
  T1.resetShow();
  T1.showRow(start, end);
}
function searchId() {
  T1.resetShow();
  let searchId = parseInt($("#Id").val());
  let r = T1.search("id", searchId);
  let rowIndex = $(r).index();
  T1.showRow(rowIndex, rowIndex);
}

var T2 = new sheet3({
  id: "t2",
  row: 20,
  col: 5,
  type: "edit",
  location: "T2",
  style: "MD",
  mode: "horzontial",
  data: STOCKJSON,
});
T2.createTable();

function marketSum() {
  alert(T2.sum(1));
}
function stockSum() {
  alert(T2.sum(2));
}

function marketAvg() {
    alert(T2.avg(1));
  }
  function stockAvg() {
    alert(T2.avg(2));
  }

  function mLtoH() {
      T2.sortByCol(1, 'startLow')
  }

  function mHtoL() {
    T2.sortByCol(1, 'startHigh')
}

function sLtoH() {
    T2.sortByCol(2, 'startLow')
}

function sHtoL() {
  T2.sortByCol(2, 'startHigh')
}

function showallStock() {
  T2.resetShow();
}

function searchStock() {
  T2.resetShow();
  let stock = parseInt($("#StockId").val());
  let r = T2.search("id", stock);
  let rowIndex = $(r).index();
  T2.showRow(rowIndex, rowIndex);
}
